# Generated by Django 4.2.7 on 2026-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'سؤال', 'verbose_name_plural': 'الأسئلة'},
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='أدخل: A أو B أو C أو D أو True أو False', max_length=5, verbose_name='الإجابة الصحيحة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, help_text='يترك فارغاً للأسئلة True/False', max_length=255, verbose_name='الخيار أ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, verbose_name='الخيار ب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, verbose_name='الخيار ج'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, verbose_name='الخيار د'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice (4 options)'), ('TF', 'True/False')], default='MCQ', max_length=3, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='اكتب السؤال بوضوح', verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='quiz_questi_order_0a027d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='quiz_questi_questio_004b7f_idx'),
        ),
    ]
